420 change github workflow to run test with feature flags (#488)
* restructure imports for update, relevant modifications of chain extensions

* WIP fixing std issue

* modification toml pendulum, orml-currencies, amplitude

* adding pallets to sibling chain

* compile sibling tests with emulator macros, fixing tests

* remove .txt files

* Revert "format nightly for latest changes"

This reverts commit e03041e0fb505706d029a69f2810ad47fa4a0336.

* generate weights for dia-oracle pallet

* re-introduce non local definition flag for clippy

* remove temporary dia-oracle fix branch

* run fmt nightly

* add benchmarkings (those not failed), modify config to use default weight

* Revert "add benchmarkings (those not failed), modify config to use default weight"

This reverts commit 79012a103e1f57fcefa852a91691307ba338b69d.

* fix benchmark for orml-tokens-management, add benchmark helper script, run benchmarks

* initial push. Does not
```
error[E0046]: not all trait items implemented, missing: `try_successful_origin`
  --> /Users/b.carlayap/.cargo/git/checkouts/cumulus-59522f43471fa161/f603a61/parachains/runtimes/assets/common/src/foreign_creators.rs:28:1
   |
28 | / impl<
29 | |         IsForeign: ContainsPair<MultiLocation, MultiLocation>,
30 | |         AccountOf: Convert<MultiLocation, AccountId>,
31 | |         AccountId: Clone,
...  |
36 | |     RuntimeOrigin::PalletsOrigin:
37 | |         From<XcmOrigin> + TryInto<XcmOrigin, Error = RuntimeOrigin::PalletsOrigin>,
   | |___________________________________________________________________________________^ missing `try_successful_origin` in implementation
   ```
   just yet

* fix https://github.com/pendulum-chain/pendulum/actions/runs/10076985515/job/27858509228?pr=488#step:8:1708 and diagnostic issue

* rebase with polkadot-v1.1.0; removed mocktopus

* fix unimplemented runtime-benchmarks

* fix invalid array

* fix unimplemented traits and run in workflow

* https://github.com/pendulum-chain/pendulum/pull/488#issuecomment-2343128993

* run workflow on edited

* do not specify type or branch

* completely remove nightly

* https://github.com/pendulum-chain/pendulum/actions/runs/10827044810/job/30039330371#step:5:1949

* set the features, remove `--all`

* integration-test does not need the `runtime-benchmarks` and `try-runtime`

move the benchmark to another workflow

* rename the workflow name

* revert to ubuntu-20

* clear disk space

* add back the accidentally deleted checkout

* revert to latest because of https://github.com/rust-lang/rustup/issues/3581

* reapply the other cleans

* fix CI

* remove bandersnatch

update CI to 1 file only

* revert from https://github.com/pendulum-chain/pendulum/pull/488/commits/71396e6a6d22e29b5863b79a5ea20f36527df627

* rebase and fix yml files.

* fix issues unrelated to this ticket

---------

Co-authored-by: Gianfranco <g.tasteri@gmail.com>